### ISSUE TITLE
Double definitions

### ISSUE THREAD

**Issue by mottosso** [sonictk/maya_python_c_extension#1]
Hi @sonictk,

Stumbled upon this tutorial via searching the interwebs for resources involving pybind11, and this hit the spot; I've got a C++ project with a custom node and want Python bindings for it, without including the C++ project into the Python project itself.

I've taken a crack at unrolling the unity-build and [re-formatted the `.bat`](https://github.com/mottosso/maya_python_c_extension/blob/ef93f9a9dfe382b9f35b1efd4c87945a12481d11/build.bat) to try and understand how things work, but there's one thing I cannot get my head around. In [my fork](https://github.com/mottosso/maya_python_c_extension) I cannot get around including the definitions for functions exposed via Python into the Python module itself. I think the same applies to this original repository as well (though there are a-few-too-many layers of indirection for me to say definitively).

Let's say the Maya plug-in was much larger and depended on a number of additional third-party dependencies (like Boost). In that case, I would expect a Python binding to merely reference the definitions coming from the plug-in, rather than re-define them. Is that the goal of this repository as well or did I misinterpret?

If so, I've managed to boil the project down into..

- [`module_main.cpp`](https://github.com/mottosso/maya_python_c_extension/blob/ef93f9a9dfe382b9f35b1efd4c87945a12481d11/cpp/module_main.cpp) and..
- [`plugin_main.cpp`](https://github.com/mottosso/maya_python_c_extension/blob/ef93f9a9dfe382b9f35b1efd4c87945a12481d11/cpp/plugin_main.cpp)

But as you can see, they both provide definitions. I would expect only one of these to actually *need* definitions, preferably the `plugin_main.cpp` which I expect to run without the added Python bindings.

Any suggestions?

**Comment by mottosso** [comment]
> Sometime later

I added a few things to force the behavior I was looking for. But what I'm not sure about is whether this was already supposed to happen?

https://github.com/mottosso/maya_python_c_extension/commit/e555b6823e62953b6941f4c0bc001c432a8db71b

The key is in [`test.py`](https://github.com/mottosso/maya_python_c_extension/blob/e555b6823e62953b6941f4c0bc001c432a8db71b/test.py), where..

1. The Maya plug-in is loaded separately
2. The Maya plug-in initialises a value
3. The Python module is loaded separately
4. The Python modulereferences the modified value

Hence highlighting that we're able to access the already-loaded Maya plug-in from a newly loaded Python module, without the Maya plug-in explicitly being aware of the Python module. That's what I'm looking for. A completely separate Python module.

It's relying on (possibly Window-specific) behavior of a dynamic library being loaded a second time returns a reference to the previously loaded library (much like how Python returns previously imported modules). It seems to work, and I think I can work around the differing methods for loading libraries between Windows and Linux.

But the question is, have I implemented something different from the original intent of this repository?

**Comment by sonictk** [comment]
Hi @mottosso:

I'm not quite sure what you're trying to achieve specifically, but I'll try to go over your fork when I get a chance. Quick OTOH answers to your questions though:

> In my fork I cannot get around including the definitions for functions exposed via Python into the Python module itself. I think the same applies to this original repository as well (though there are a-few-too-many layers of indirection for me to say definitively).
The tutorial IIRC is demonstrating two approaches: one is having your exposing your Python extensions available upon loading the Maya plug-in immediately (though this has issues as discussed in the tutorial), and the second is building your Python extension as a conventional `.pyd` DLL that can be loaded like a normal compiled Python C extension module. There's no indirection involved here.

> Let's say the Maya plug-in was much larger and depended on a number of additional third-party dependencies (like Boost). In that case, I would expect a Python binding to merely reference the definitions coming from the plug-in, rather than re-define them. Is that the goal of this repository as well or did I misinterpret?
Not sure I quite understand the question; the Python extension module is compiled with the logic "coming" from the plug-in; it isn't "re-defining" it: the hello world example shows the main logic in https://github.com/sonictk/maya_python_c_extension/blob/master/maya_python_c_ext_hello_world.cpp and the Python extension module binding is in: https://github.com/sonictk/maya_python_c_extension/blob/master/maya_python_c_ext_py_hello_world.cpp which references it. Dependencies or unity builds have nothing to do with it.

> If so, I've managed to boil the project down into...
Looking at your two files very quickly, yea, I wouldn't expect you to define the same function that way; see above. That's not what is going on in the sample code provided.

> The key is in test.py, where..

>    The Maya plug-in is loaded separately
>   The Maya plug-in initialises a value
>    The Python module is loaded separately
>    The Python modulereferences the modified value

This is not something the original tutorial implements for a variety of reasons, since what you're describing according to those steps is essentially modifying memory across DLL boundaries, which for me is generally a big no-no for several reasons (this being one of them: https://devblogs.microsoft.com/oldnewthing/20060915-04/?p=29723). Ideally both DLLs would be modifying memory already allocated by the host application instead of modifying memory that either of the DLLs have allocated themselves, unless you guarantee the allocation mechanisms are going to be the same for both. Or, if constraints allow, you could rely on the most classic way of inter-DLL/process communication: serializing to disk the data you're attempting to have both DLLs share and having both DLLs read from there instead, with additional synchronization mechanisms as needed.

P.S. You could also consider the approach in the tutorial where you expose the Python bindings upon loading the Maya plug-in immediately, rather than having to load a separate Python `.pyd` DLL as well, so that you don't have to introduce these sorts of synchronization problems across DLL boundaries.

(That doesn't mean you _shouldn't attempt the 4 steps you've outlined above, I've successfully done something like that in production before albeit for completely different reasons not involving Maya/Python, but I'd be interested in hearing the actual use case for this before recommending you go ahead with that sort of approach.)

Hopefully that makes sense!
